### ISSUE TITLE
Consider Global Integrity reports for states and countries

### ISSUE THREAD

**Issue by thadk** [thinkcontext/Think-Context#36]
I can post more detail if there is interest, but consider adding the report cards for US States or international countries written in a careful way by journalists in each of those regions.

https://www.globalintegrity.org/global-report/what-is-gi-report/
http://www.stateintegrity.org/your_state

**Comment by thinkcontext** [comment]
Hmm, don't currently have any place related data but the idea is interesting.  I'm trying to wrap my head around what "contexts" the extension should notify a user about place.  Fitting with the current model it would be when they encountered, say, the website of the government or the Wikipedia page.  Did you have other things in mind?

I'd be willing to give it a try, any interest in writing a scraper?
